apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opendkim.fullname" . }}-silver
  labels:
    {{- include "opendkim.labels" . | nindent 4 }}
type: Opaque
stringData:
  silver.yaml: |
    domains:
{{- range .Values.domains }}
      - domain: {{ .domain | quote }}
        dkim-selector: {{ default "mail" .dkimSelector | quote }}
        dkim-key-size: {{ default 2048 .dkimKeySize }}
{{- end }}
