#!/bin/bash
#
# This script initializes the postfix config files

# --- Sanity Checks & Configuration ---
set -euo pipefail

# Define constant paths
readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly ROOT_DIR="$(dirname "$(dirname "$SCRIPT_DIR")")"
readonly SILVER_YAML_FILE="${ROOT_DIR}/silver.yaml"
readonly DKIM_DATA_PATH="${ROOT_DIR}/silver-config/gen/opendkim"
readonly DKIM_SELECTOR=mail

# --- Main Logic ---
readonly MAIL_DOMAIN=$(grep -m 1 '^domain:' "${SILVER_YAML_FILE}" | sed 's/domain: //' | xargs)

export RELAYHOST=$(yq -e '.relayhost' "$CONFIG_FILE" || echo "")

# --- Derived variables ---
MAIL_HOSTNAME=${MAIL_HOSTNAME:-mail.$MAIL_DOMAIN}
VMAIL_DIR="/var/mail/vmail"

# --- Generate main.cf content ---
cat << EOF
#
# Postfix main.cf generated by postfix.sh
#

# --- Basic Postfix configuration ---
myhostname = $MAIL_HOSTNAME
myorigin = /etc/mailname
mydomain = $MAIL_DOMAIN
mydestination = localhost.localdomain, localhost
inet_interfaces = all
inet_protocols = ipv4
mynetworks = 127.0.0.0/8
relayhost = $RELAYHOST

# --- Logging for Docker ---
maillog_file = /dev/stdout

# --- TLS ---
smtpd_tls_cert_file = /etc/letsencrypt/live/$MAIL_DOMAIN/fullchain.pem
smtpd_tls_key_file = /etc/letsencrypt/live/$MAIL_DOMAIN/privkey.pem
smtpd_tls_CAfile = /etc/ssl/certs/ca-certificates.crt
smtpd_use_tls = yes
smtpd_tls_security_level = may

# --- SASL authentication via Dovecot ---
smtpd_sasl_type = dovecot
smtpd_sasl_path = private/auth
smtpd_sasl_auth_enable = yes
smtpd_sasl_security_options = noanonymous
broken_sasl_auth_clients = yes

# --- Virtual mailbox configuration ---
virtual_mailbox_domains = hash:/etc/postfix/virtual-domains
virtual_mailbox_maps = hash:/etc/postfix/virtual-users
virtual_alias_maps = hash:/etc/postfix/virtual-aliases
virtual_mailbox_base = $VMAIL_DIR
virtual_transport = lmtp:unix:private/dovecot-lmtp
virtual_minimum_uid = 5000
virtual_uid_maps = static:5000
virtual_gid_maps = static:8

# --- Submission service overrides ---
submission_service_override = submission inet n - y - - smtpd
submission_service_override_syslog_name = postfix/submission
submission_service_override_smtpd_tls_security_level = encrypt
submission_service_override_smtpd_sasl_auth_enable = yes
submission_service_override_smtpd_tls_auth_only = yes
submission_service_override_smtpd_relay_restrictions = permit_sasl_authenticated,reject
submission_service_override_smtpd_milters = inet:rspamd-server:11332,inet:opendkim-server:8891

# --- Milter (Rspamd + DKIM) ---
milter_protocol = 6
milter_default_action = accept
smtpd_milters = inet:rspamd-server:11332,inet:opendkim-server:8891
non_smtpd_milters = inet:rspamd-server:11332,inet:opendkim-server:8891

# --- Throttling / Abuse control ---
smtpd_client_connection_rate_limit = 10
smtpd_client_message_rate_limit = 100
smtpd_client_recipient_rate_limit = 200
smtpd_recipient_limit = 50
anvil_rate_time_unit = 60s
smtpd_client_connection_count_limit = 20
EOF